[build-system]
requires = ["setuptools>=64", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pytorch_sphinx_theme"
version = "0.0.24"
authors = [
    {name = "Shift Lab", email = "info@shiftlabny.com"},
]
description = "PyTorch Sphinx Theme"
readme = "README.md"
license = {text = "MIT"}
requires-python = ">=3.8"
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Environment :: Web Environment",
    "Intended Audience :: Developers",
    "Intended Audience :: System Administrators",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Topic :: Internet",
    "Topic :: Software Development :: Documentation",
]
dependencies = [
    "sphinx>=4.0.0",
    "docutils>=0.18.1,<0.21",
]

[project.urls]
Homepage = "https://github.com/pytorch/pytorch_sphinx_theme"
Repository = "https://github.com/pytorch/pytorch_sphinx_theme"
Issues = "https://github.com/pytorch/pytorch_sphinx_theme/issues"

[project.entry-points."sphinx.html_themes"]
pytorch_sphinx_theme = "pytorch_sphinx_theme"

[project.entry-points."sphinx.builders"]
pytorch_sphinx_theme = "pytorch_sphinx_theme"

[tool.setuptools.packages.find]
include = ["pytorch_sphinx_theme*"]

[tool.setuptools.package-data]
pytorch_sphinx_theme = [
    "theme.conf",
    "*.html",
    "static/css/*.css",
    "static/js/*.js",
    "static/fonts/*.*",
    "static/images/*.*",
    "theme_variables.jinja"
]